name: Check and Publish

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - name: Cargo Format
        uses: actions-rs/cargo@v1
        with:
          commands: fmt
          args: --all -- --check

      - name: Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          
  publish:
    if: github.event.name == 'release'
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to crates.io
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
